## Learning Numpy Arrays ##
### What is an Array? ###
Arrays are a fundamental data structure, and an important part of most programming languages. <br/>
In Python, they are containers which are able to store more than one item at the same time. <br/>
Specifically, they are an ordered collection of elements with every value being of the same data type. <br/>

### What is the function arrange? ###
The arange([start,] stop[, step,][, dtype]) : <br/>
Returns an array with evenly spaced elements as per the interval. <br/>
The interval mentioned is half-opened i.e. [Start, Stop) 

<br/><br/>
https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html

In [1]:
import numpy as np

In [2]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

### Array Indexing ###

In [6]:
#Calling the first array
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
#call the first value in x1
x1[0] # <-- reminds me of calling the first value in a list

5

In [8]:
# calls the fifth value in the array
x1[4]

7

In [9]:
# calls the last value in the array
x1[-1]

9

In [10]:
# calls the fifth value in the array
x1[-2]

7

### Multi-Dimensional Arrarys ###
In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
# call the first value in the first tuple(?) 
# Is it a tuple? I thought that tuples were in parathesis
x2[0,0]

3

In [13]:
# call the first value in the last tuple
x2[2,0]

1

In [14]:
# call the last value in the last tuple
x2[2,-1]

7

Values can also be modified using any of the above index notation:

In [15]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. <br/> 
This means, for example, that if you attempt to insert a floating-point value to an integer array,<br/> 
the value will be silently truncated. Don't be caught unaware by this behavior!

In [16]:
x1[0] = 3.14159  # this will be truncated! I guess you can't use decimals to change the first result?
x1

array([3, 0, 3, 3, 7, 9])

### What are Subarrays? ###
A subarray is a contiguous part of array. An array that is inside another array. <br/>
For example, consider the array [1, 2, 3, 4], There are 10 non-empty sub-arrays. <br/>
The subarrays are (1), (2), (3), (4), (1,2), (2,3), (3,4), (1,2,3), (2,3,4) and (1,2,3,4)<br/><br/>

It appears to me that subarrays are like the results you pull when slicing lists. <br/>
I need to do some more research about the difference between <i>tuples, lists, and arrays.<i/>
    
They all look the same to me. <br/><br/>

### Array Slicing: Accessing Subarrays ###
Just as we can use square brackets to access individual array elements, <br/>
we can also use them to access subarrays with the slice notation, <br/>
marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; <br/>
to access a slice of an array x, use this: (<b> x[start:stop:step] <b/>)<br/>

If any of these are unspecified, they default to the values start=0, <br/>
stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-Dimensional Subarrays ###

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])